apiVersion: v1
kind: Service
metadata:
  name: rfpintels-userservices
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: rfpintels-userservices
spec:
  selector:
    app: rfpintels-userservices
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rfpintels-userservices
  namespace: rfpintels-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rfpintels-userservices
  template:
    metadata:
      labels:
        app: rfpintels-userservices
    spec:
      containers:
      - name: rfpintels-userservices
        image: rfpintelscontainer.azurecr.io/userservices/rfpintels-userservices:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          value: "dev"